name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install pipenv
      run: python -m pip install pipenv
    - name: install conan
      run: $HOME/.local/bin/pipenv install conan
