name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install pipenv
      run: python3 -m pip install pipenv
    - name: CMake configuration
      run: cmake -DCMAKE_MESSAGE_LOG_LEVEL=DEBUG -B $HOME/build $GITHUB_WORKSPACE
