name: C/C++ CI
on:
  push:
    branches: [ master ]
jobs:
  build-and-test:
    name: Ubuntu
    strategy:
      matrix:
        cpp_standard: [ 11, 14, 17, 20 ]
        cpp_compiler: [ g++-8, g++-9, clang++-8, clang++-9 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: install venv
        run: apt-get install python3-venv
      - name: install poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: CMake configuration
        run: >
          cmake -B build $GITHUB_WORKSPACE
          -DCMAKE_BUILD_TYPE=RELEASE -DPoetry_ROOT_DIR=$HOME/.poetry/bin
          -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}} -DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}}
      - name: Build
        run: cmake --build build --config release
      - name: Run tests
        run: ctest
        working-directory: build/tests
