name: C/C++ CI
on:
  push:
    branches: [ master ]
jobs:
  build-and-test:
    name: Windows
    strategy:
      matrix:
        cpp_standard: [ 11, 14, 17, 20 ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: install poetry
        run: (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python
      - name: CMake configuration
        run: >
          cmake -B build $env:GITHUB_WORKSPACE
          -DPoetry_DIR="$env:USERPROFILE\.poetry"
          -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}}
      - name: Build
        run: cmake --build build --config release
      - name: Run tests
        run: ctest -C release
        working-directory: build/tests
